import json
import math
import os

import cv2
import gradio as gr
import numpy as np
import torch
import torch.nn as nn
from PIL import Image

WEIGHTS_DIR = "weights"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ---------- shared DCGAN generator template (same as notebooks/02-04) ----------
def _gen_config(img_size):
    for init in (4, 7):
        if img_size % init == 0:
            n = img_size // init
            steps = int(math.log2(n))
            if init * (2**steps) == img_size:
                return init, steps
    raise ValueError(f"unsupported img_size {img_size}")


class Generator(nn.Module):
    def __init__(self, img_size, nz=100, ngf=64, channels=3):
        super().__init__()
        init_size, steps = _gen_config(img_size)
        mult = 2 ** max(steps - 1, 0)
        cur = ngf * mult
        layers = [
            nn.ConvTranspose2d(nz, cur, init_size, 1, 0, bias=False),
            nn.BatchNorm2d(cur),
            nn.ReLU(True),
        ]
        for i in range(steps):
            last = i == steps - 1
            nxt = channels if last else cur // 2
            layers.append(nn.ConvTranspose2d(cur, nxt, 4, 2, 1, bias=False))
            if last:
                layers.append(nn.Tanh())
            else:
                layers.append(nn.BatchNorm2d(nxt))
                layers.append(nn.ReLU(True))
            cur = nxt
        self.net = nn.Sequential(*layers)

    def forward(self, z):
        return self.net(z)


# ---------- weight availability (drives graceful degradation) ----------
def wpath(name):
    return os.path.join(WEIGHTS_DIR, name)


ESRGAN_GENERAL_PATH = wpath("RealESRGAN_x4plus.pth")
ESRGAN_ANIME_PATH = wpath("RealESRGAN_x4plus_anime_6B.pth")
ESRGAN_VARIANTS = []
if os.path.exists(ESRGAN_GENERAL_PATH):
    ESRGAN_VARIANTS.append("general")
if os.path.exists(ESRGAN_ANIME_PATH):
    ESRGAN_VARIANTS.append("anime")

# Each dataset can be generated by whichever architectures have been trained.
ARCHS = ["dcgan", "lsgan", "wgan_gp"]
ARCH_LABEL = {"dcgan": "DCGAN", "lsgan": "LSGAN", "wgan_gp": "WGAN-GP"}
BEST_CHOICE = "best (winner)"

# (prefix, tab title, img_size, channels, noun)
GEN_DATASETS = [
    ("mnist", "Generate Digit", 28, 1, "MNIST digits"),
    ("anime", "Generate Anime Face", 64, 3, "anime faces"),
]

try:
    with open(wpath("winners.json")) as f:
        WINNERS = json.load(f)
except (OSError, ValueError):
    WINNERS = {}


def gen_choices(prefix):
    """Model-variant options for a dataset: the winner (if promoted) plus any
    per-architecture weights that exist."""
    choices = []
    if os.path.exists(wpath(f"{prefix}_generator.pth")):
        win = WINNERS.get(prefix)
        label = f"{BEST_CHOICE}" + (f" — {ARCH_LABEL[win]}" if win in ARCH_LABEL else "")
        choices.append((label, "best"))
    for a in ARCHS:
        if os.path.exists(wpath(f"{prefix}_{a}_generator.pth")):
            choices.append((ARCH_LABEL[a], a))
    return choices


NOT_READY_MSG = "### Model not yet trained — check back soon."


# ---------- Real-ESRGAN upscaling ----------
_esrgan_cache = {}


def get_upsampler(variant):
    if variant in _esrgan_cache:
        return _esrgan_cache[variant]
    from basicsr.archs.rrdbnet_arch import RRDBNet
    from realesrgan import RealESRGANer

    if variant == "anime":
        model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=6, num_grow_ch=32, scale=4)
        path = ESRGAN_ANIME_PATH
    else:
        model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23, num_grow_ch=32, scale=4)
        path = ESRGAN_GENERAL_PATH

    upsampler = RealESRGANer(
        scale=4,
        model_path=path,
        model=model,
        tile=256,        # tile the image so large inputs don't exhaust CPU memory
        tile_pad=10,
        pre_pad=0,
        half=torch.cuda.is_available(),
        device=DEVICE,
    )
    _esrgan_cache[variant] = upsampler
    return upsampler


# cap input size so a 4x upscale stays within the free CPU Space's memory
MAX_INPUT_SIDE = 768


def upscale_image(image, variant, factor):
    if image is None:
        raise gr.Error("Upload an image first.")
    img = image.convert("RGB")
    w, h = img.size
    if max(w, h) > MAX_INPUT_SIDE:
        s = MAX_INPUT_SIDE / max(w, h)
        img = img.resize((max(1, int(w * s)), max(1, int(h * s))), Image.LANCZOS)
    img_bgr = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    try:
        output, _ = get_upsampler(variant).enhance(img_bgr, outscale=factor)
    except Exception as e:  # never hard-crash the tab
        raise gr.Error(f"Upscaling failed: {e}")
    return Image.fromarray(cv2.cvtColor(output, cv2.COLOR_BGR2RGB))


# ---------- DCGAN sample generation ----------
_gen_cache = {}


def load_generator(path, channels, img_size, nz=100):
    if path not in _gen_cache:
        model = Generator(img_size=img_size, nz=nz, channels=channels).to(DEVICE)
        model.load_state_dict(torch.load(path, map_location=DEVICE))
        model.eval()
        _gen_cache[path] = model
    return _gen_cache[path]


def make_big_grid(model, img_size, channels, n=16, cols=4, pad=6, target=760):
    """4x4 sample grid, upscaled so digits/faces are actually visible on screen."""
    with torch.no_grad():
        imgs = model(torch.randn(n, 100, 1, 1, device=DEVICE)).cpu().clamp(-1, 1)
    imgs = ((imgs + 1) / 2).numpy()
    rows = n // cols
    canvas = np.full((rows * img_size + (rows + 1) * pad,
                      cols * img_size + (cols + 1) * pad, 3), 255, np.uint8)
    for i in range(n):
        img = imgs[i]
        if channels == 1:
            img = np.repeat(img, 3, axis=0)
        img = (img.transpose(1, 2, 0) * 255).astype(np.uint8)
        r, c = divmod(i, cols)
        y, x = pad + r * (img_size + pad), pad + c * (img_size + pad)
        canvas[y:y + img_size, x:x + img_size] = img
    pil = Image.fromarray(canvas)
    scale = target / max(canvas.shape[:2])
    resample = Image.NEAREST if channels == 1 else Image.LANCZOS  # NEAREST keeps digits crisp
    return pil.resize((int(canvas.shape[1] * scale), int(canvas.shape[0] * scale)), resample)


def make_generate_fn(prefix, img_size, channels):
    def _generate(choice):
        arch = None if (choice is None or choice == "best") else choice
        path = wpath(f"{prefix}_generator.pth" if arch is None else f"{prefix}_{arch}_generator.pth")
        if not os.path.exists(path):
            raise gr.Error("That model variant isn't available yet.")
        return make_big_grid(load_generator(path, channels, img_size), img_size, channels)
    return _generate


# ---------- UI ----------
with gr.Blocks(title="image-lab") as demo:
    gr.Markdown(
        "# image-lab\n"
        "Image **synthesis** — GANs trained from scratch (DCGAN / LSGAN / WGAN-GP) — and "
        "**restoration** via Real-ESRGAN super-resolution, in one app."
    )

    with gr.Tab("Upscale"):
        if ESRGAN_VARIANTS:
            gr.Markdown("Real-ESRGAN 4x super-resolution. The effect is clearest on small or "
                        "blurry inputs; the *anime* variant differs from *general* mainly on illustrations.")
            with gr.Row():
                with gr.Column():
                    upscale_input = gr.Image(type="pil", label="Input image")
                    variant_dd = gr.Dropdown(ESRGAN_VARIANTS, value=ESRGAN_VARIANTS[0], label="Model variant")
                    factor_slider = gr.Slider(2, 4, value=4, step=1, label="Upscale factor")
                    upscale_btn = gr.Button("Upscale", variant="primary")
                with gr.Column():
                    upscale_output = gr.Image(type="pil", label="Result", show_download_button=True)
            upscale_btn.click(upscale_image, [upscale_input, variant_dd, factor_slider], upscale_output)
        else:
            gr.Markdown(NOT_READY_MSG)

    for _prefix, _title, _size, _ch, _noun in GEN_DATASETS:
        with gr.Tab(_title):
            _choices = gen_choices(_prefix)
            if _choices:
                gr.Markdown(f"Sampled from the generator trained on {_noun}.")
                _dd = gr.Dropdown([c[0] for c in _choices], value=_choices[0][0], label="Model")
                _val_of = {label: val for label, val in _choices}
                _btn = gr.Button("Generate 16 samples", variant="primary")
                _out = gr.Image(type="pil", label="Samples", show_download_button=True, height=520)
                _fn = make_generate_fn(_prefix, _size, _ch)
                _btn.click(lambda label, f=_fn, m=_val_of: f(m[label]), _dd, _out)
            else:
                gr.Markdown(NOT_READY_MSG)


if __name__ == "__main__":
    demo.launch(share=True)
